name       : intltool
version    : 0.51.0
release    : 5
source     :
    - https://launchpad.net/intltool/trunk/0.51.0/+download/intltool-0.51.0.tar.gz : 67c74d94196b153b774ab9f89b2fa6c6ba79352407037c8c14d5aeb334e959cd
license    :
    - GPL-2.0
summary    : intltool (Tools to translate different file formats)
component  : system.devel
builddeps  :
    - perl
    - perl-xmlparser
patterns   :
    - /usr/share/aclocal
description: |
    intltool is a set of tools to centralize translation of many different file formats using GNU gettext-compatible PO files.
setup      : |
    %patch -p1 < $pkgfiles/perl-5.26-fix.patch
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
